# .streamlit/secrets.toml
# ⚠️ NÃO COMMITE ESTE ARQUIVO no Git!
# Preencha com as credenciais reais do seu projeto Supabase.

[supabase]
url = "https://gquwpdkgzbbjgaqoktcx.supabase.co/rest/v1/"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdXdwZGtnemJiamdhcW9rdGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NDY5MDYsImV4cCI6MjEwNTIyMjkwNn0.aqFg8SSiGmD5sic9oJ2gdDjn_gC3EEoYicB_MmiLG-U"
